### ISSUE TITLE
👋 are you open to PRs?

### ISSUE THREAD

**Issue by leoebfolsom** [bruno-szdl/dbt-ci-cd#11]
Would love to propose an idea or two if you're open to collab! Thanks for the shoutout on LinkedIn and for putting this awesome resource together!

**Comment by bruno-szdl** [comment]
Sure! I am open to new ideas! I just want to make it as simple as possible and easy to understand, so people can use it with ease

**Comment by leoebfolsom** [comment]
Thanks! I _think_ you might need to add me as a contributor, or change general permissions? Or am I doing something wrong? 🙇 
<img width="1107" alt="Screenshot 2024-05-28 at 08 56 23" src="https://github.com/bruno-szdl/dbt-ci-cd/assets/1799931/361a7e90-10c6-4356-a04b-37dc83089b12">

**Comment by bruno-szdl** [comment]
Done!
